### ISSUE TITLE
Question: How do you use these files?

### ISSUE THREAD

**Issue by kwelch** [kentcdodds/dotfiles#1]
Kent, 

How many of these files can you source to the repo version and how many do you copy into place?

I have started to get my file set to a place that I like them and would like to gather them as you have, but I am unsure how to leverage them so I am not just copying them all the time. 

Thanks, 
--Kyle

**Comment by kentcdodds** [comment]
Ummm... I think that I symlink most of the files in my dotfiles :) Does that answer your question?

**Comment by kwelch** [comment]
Enough that I am comfortable closing and intrigued enough to go learn more. 👍
