### ISSUE TITLE
Illegal Flag error on git diff

### ISSUE THREAD

**Issue by catmclough** [kentcdodds/dotfiles#13]
Hey Kent,

I'm attempting to repurpose these dotfiles (which are awesome and super helpful, btw!) but I've run into an issue with `git diff` that I'm having a hard time tracking down.

```
$ git diff
Illegal flag: -theme
```

I'm not seeing a `-theme` flag used anywhere in your .zshrc or .gitconfig so I'm a bit stuck. Would you happen to have any suggestions?

**Comment by kentcdodds** [comment]
I use [delta](https://github.com/dandavison/delta) 😁

**Comment by kentcdodds** [comment]
https://github.com/kentcdodds/dotfiles/blob/main/.gitconfig#L21

**Comment by catmclough** [comment]
Aha! Think the .macos script might need to be updated to install `git-delta` instead of `delta`: https://github.com/kentcdodds/dotfiles/blob/main/.macos#L43

https://github.com/dandavison/delta#installation

Thank you!

**Comment by kentcdodds** [comment]
Oh, thank you!
